### ISSUE TITLE
community/roadmap.md, community/style_guide.md, deploy/s3.md, install/_index.yaml, install/pip.html and install/source_windows.md

### ISSUE THREAD

**Issue by leviding** [xitu/tensorflow-docs#122]
* Markdown 文件：
    * [x] [community/roadmap.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/roadmap.md)
    * [x] [community/style_guide.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/community/style_guide.md)
    * [x] [deploy/s3.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/deploy/s3.md)
    * [x] [install/_index.yaml](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/_index.yaml)
    * [x] [install/pip.html](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/pip.html)
    * [x] [install/source_windows.md](https://github.com/xitu/tensorflow-docs/blob/zh-hans/install/source_windows.md)
  * PR 地址：https://github.com/xitu/tensorflow-docs/pull/134
  **注意**：这些内容以几个 PR 提交均可，看你的安排。

  ----

  * 翻译时间：10 天
  * 校对时间：3 天
  * 翻译积分：10 分
  * 校对积分：2-5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

**Comment by leviding** [comment]
由 @sisibeloved 翻译
